### ISSUE TITLE
tearDown() still outperforms the Accelerator

### ISSUE THREAD

**Issue by BentCoder** [mybuilder/phpunit-accelerator#14]
Hi,

This is certainly a useful thing to use. I've done small benchmark and wish to share because I think there is still room to improve this library.

Thanks

`OK (4011 tests, 11023 assertions)`

This is without `tearDown()` and PHPUnit Accelerator.

```
Time: 5.22 seconds, Memory: 42.00MB
Time: 5.31 seconds, Memory: 42.00MB
Time: 5.27 seconds, Memory: 42.00MB
```

This is `tearDown()` only version.

```
Time: 5.27 seconds, Memory: 18.00MB
Time: 5.36 seconds, Memory: 18.00MB
Time: 5.29 seconds, Memory: 18.00MB
```

This is PHPUnit Accelerator only version.

```
Time: 5.66 seconds, Memory: 28.00MB
Time: 5.60 seconds, Memory: 28.00MB
Time: 5.58 seconds, Memory: 28.00MB
```

This is with `tearDown()` and PHPUnit Accelerator version.

```
Time: 5.61 seconds, Memory: 28.00MB
Time: 5.66 seconds, Memory: 28.00MB
Time: 5.57 seconds, Memory: 28.00MB
```

**Comment by b1rdex** [comment]
Hi @BentCoder. What do you mean by `tearDown() only version`?

**Comment by BentCoder** [comment]
`tearDown()` only - Only `tearDown()` is used in application. No PHPUnit Accelerator is enabled at all.

`PHPUnit Accelerator` only = Only PHPUnit Accelerator is enabled in application. `tearDown()` is not used at all.

Clear enough?

**Comment by b1rdex** [comment]
No, it's not clear :). What code do you have in `tearDown` method?

**Comment by gavinlove** [comment]
@BentCoder Which version of PHPUnit are you using? 

Some of the changes recently have made me wonder if this is as good as it used to be because I think PHPUnit has improved the areas this takes advantage of. 

I will try to do some benchmarks.

**Comment by gavinlove** [comment]
@BentCoder Also I agree with @b1rdex without knowing what you are doing in the `tearDown` it is hard to evaluate what you are saying,

**Comment by BentCoder** [comment]
This is a `tearDown` only example where I don't have `PHPUnit Accelerator` library anywhere in my application because there is no such library called `PHPUnit Accelerator` in the World!

```
class YouTest extends PHPUnit_Framework_TestCase
{
   private $one;
   private $two;
   private ..... // And a few more

   public function setUp()
   {
      $this->one = //whatever;
      $this->two = //whatever;
   }

   public function testWhatever()
   {
      $this->three = //whatever;
      $this->four = //whatever;
   }

   public function tearDown()
   {
      $this->one = null;
      $this->two = null;
   }
}
```

Benchark:
```
Time: 5.27 seconds, Memory: 18.00MB
Time: 5.36 seconds, Memory: 18.00MB
Time: 5.29 seconds, Memory: 18.00MB
```

--------
This is a `PHPUnit Accelerator` only example where I don't have `tearDown` method used anywhere in my tests because Sebastian hasn't thought about implementing the methods yet!

```
class YouTest extends PHPUnit_Framework_TestCase
{
   private $one;
   private $two;
   private ..... // And a few more

   public function setUp()
   {
      $this->one = //whatever;
      $this->two = //whatever;
   }

   public function testWhatever()
   {
      $this->three = //whatever;
      $this->four = //whatever;
   }
}
```

And I have this [part](https://github.com/mybuilder/phpunit-accelerator#usage) in my phpunit.xml file and obviously added the library with composer.

Benchmark:

```
Time: 5.66 seconds, Memory: 28.00MB
Time: 5.60 seconds, Memory: 28.00MB
Time: 5.58 seconds, Memory: 28.00MB
```

--------
And this is without having `tearDown` and `Accelerator` benchmark.

```
Time: 5.22 seconds, Memory: 42.00MB
Time: 5.31 seconds, Memory: 42.00MB
Time: 5.27 seconds, Memory: 42.00MB
```

--------
I bet you guys will understand what I am talking about. I am on Ubuntu 16, using PHP 7.1 and I don't know what version of PHPUnit I am using as I am not on my computer at the moment.

**Comment by BentCoder** [comment]
@b1rdex @gavinlove Just want to find out if you guys have anything to add after my detailed explanation above? Thanks.

**Comment by bentcoder** [comment]
It has been a long time. Anyone has any input?

**Comment by b1rdex** [comment]
@BentCoder I moved to phpunit 7+ and dropped phpunit accelerator.
