### ISSUE TITLE
PHPUnit 7 support

### ISSUE THREAD

**Issue by umpirsky** [mybuilder/phpunit-accelerator#17]

**Comment by lloiacono** [comment]
Any updates?

**Comment by umpirsky** [comment]
I tested my large test suite without phpunit-accelerator in PHPUnit 7, and there was no difference. So I just dropped it. I suggest trying the same.

**Comment by b1rdex** [comment]
Phpunit 7 support landed in #18 to master.

**Comment by gavinlove** [comment]
I no longer see any real difference with this so I don't think it is worth running it. We have been removing it from our projects.

**Comment by b1rdex** [comment]
> I no longer see any real difference with this so I don't think it is worth running it. We have been removing it from our projects.

@gavinlove if I understood you correctly you say that you advise to not use this plugin for phpunit >7.0.
I think this should be mentioned in readme.
Another option is to add `conflicts` section to `composer.json`.
